/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perulangan;

import com.toedter.calendar.JDateChooser;
import controller.peminjamancontroller;
import java.awt.ScrollPane;
import java.awt.event.KeyEvent;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Fikri
 */
public class formpeminjaman extends javax.swing.JFrame {

    /**
     * Creates new form formpeminjaman
     */
    peminjamancontroller peminjamancontroller;
    public formpeminjaman() {
        initComponents();
        peminjamancontroller = new peminjamancontroller(this);
    }

    public JTextField getTxtkodeanggota2() {
        return txtkodeanggota2;
    }

    public JTextField getTxtnamaanggota2() {
        return txtnamaanggota2;
    }

    public JTextField getTxtnopeminjam() {
        return txtnopeminjam;
    }

    public JDateChooser getTxttanggalkembali() {
        return txttanggalkembali;
    }

    public JTable getTableAnggota() {
        return tableAnggota;
    }

   public ScrollPane getjScrollPanAnggota() {
        return jScrollPanAnggota;
    }

   

   

    

   


   
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane11 = new javax.swing.JScrollPane();
        jTable10 = new javax.swing.JTable();
        jScrollPane18 = new javax.swing.JScrollPane();
        jTable17 = new javax.swing.JTable();
        txtnamaanggota2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtnopeminjam = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txttanggalkembali = new com.toedter.calendar.JDateChooser();
        jLabel10 = new javax.swing.JLabel();
        txtkodeanggota2 = new javax.swing.JTextField();
        tableAnggota = new javax.swing.JTable();

        jTable10.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane11.setViewportView(jTable10);

        jTable17.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane18.setViewportView(jTable17);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(null);

        txtnamaanggota2.setText("jTextField1");
        txtnamaanggota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnamaanggota2ActionPerformed(evt);
            }
        });
        txtnamaanggota2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnamaanggota2KeyPressed(evt);
            }
        });
        getContentPane().add(txtnamaanggota2);
        txtnamaanggota2.setBounds(140, 200, 210, 30);

        jLabel7.setText("Tanggal Kemabali");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(40, 100, 90, 30);

        jLabel8.setText("Nama Anggota");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(40, 200, 90, 30);

        txtnopeminjam.setText("jTextField1");
        txtnopeminjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnopeminjamActionPerformed(evt);
            }
        });
        txtnopeminjam.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtnopeminjamKeyPressed(evt);
            }
        });
        getContentPane().add(txtnopeminjam);
        txtnopeminjam.setBounds(130, 50, 210, 30);

        jLabel9.setText("No Peminjam");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(40, 50, 90, 30);
        getContentPane().add(txttanggalkembali);
        txttanggalkembali.setBounds(130, 100, 210, 30);

        jLabel10.setText("Kode Anggota");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(40, 150, 90, 30);

        txtkodeanggota2.setText("jTextField1");
        txtkodeanggota2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtkodeanggota2ActionPerformed(evt);
            }
        });
        txtkodeanggota2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtkodeanggota2KeyPressed(evt);
            }
        });
        getContentPane().add(txtkodeanggota2);
        txtkodeanggota2.setBounds(140, 150, 210, 30);

        tableAnggota.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Kode Anggota", "Nama Anggota", "Alamat"
            }
        ));
        tableAnggota.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAnggotaMouseClicked(evt);
            }
        });
        getContentPane().add(tableAnggota);
        tableAnggota.setBounds(160, 410, 300, 64);

        setBounds(0, 0, 709, 687);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnamaanggota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnamaanggota2ActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtnamaanggota2ActionPerformed

    private void txtnamaanggota2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnamaanggota2KeyPressed
        // TODO add your handling code here:
       
    }//GEN-LAST:event_txtnamaanggota2KeyPressed

    private void txtnopeminjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnopeminjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnopeminjamActionPerformed

    private void txtnopeminjamKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnopeminjamKeyPressed
        // TODO add your handling code here:
         if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            peminjamancontroller.viewTable();
        }
    }//GEN-LAST:event_txtnopeminjamKeyPressed

    private void txtkodeanggota2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtkodeanggota2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodeanggota2ActionPerformed

    private void txtkodeanggota2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtkodeanggota2KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtkodeanggota2KeyPressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_formMouseClicked

    private void tableAnggotaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAnggotaMouseClicked
        // TODO add your handling code here:
        peminjamancontroller.ambilTable();
    }//GEN-LAST:event_tableAnggotaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(formpeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(formpeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(formpeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(formpeminjaman.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new formpeminjaman().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane11;
    private javax.swing.JScrollPane jScrollPane18;
    private javax.swing.JTable jTable10;
    private javax.swing.JTable jTable17;
    private javax.swing.JTable tableAnggota;
    private javax.swing.JTextField txtkodeanggota2;
    private javax.swing.JTextField txtnamaanggota2;
    private javax.swing.JTextField txtnopeminjam;
    private com.toedter.calendar.JDateChooser txttanggalkembali;
    // End of variables declaration//GEN-END:variables
}
