
package view;
import controller.StudentRecordController;

public class FormStudentRecord extends javax.swing.JFrame {

    
    StudentRecordController controller;
    
    
    public FormStudentRecord() {
        initComponents();
        controller = new StudentRecordController(this);
        controller.bersihForm();
    }
    
    public javax.swing.JTextField getTxtName(){
       return txtname;
    }
    
    public javax.swing.JTextField getTxtAge(){
       return txtage;
    }
    
    public javax.swing.JTextField getTxtAddress(){
       return txtaddress;
    }
    
    public javax.swing.JTextField getTxtMathGrade(){
       return txtMathGrade;
    }
    
    public javax.swing.JTextField getTxtEnglishGrade(){
       return txtEnglishGrade;
    }
    
    public javax.swing.JTextField getTxtScienceGrade(){
       return txtScienceGrade;
    }
    
    public javax.swing.JTable gettabelStudentRecord(){
        return tabelStudentRecord;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtname = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtaddress = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        txtMathGrade = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtEnglishGrade = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtScienceGrade = new javax.swing.JTextField();
        btnInsert = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelStudentRecord = new javax.swing.JTable();
        btnEdit = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setText("Nama");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 100, 20);

        txtname.setText("jTextField1");
        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        getContentPane().add(txtname);
        txtname.setBounds(120, 10, 260, 30);

        jLabel2.setText("Alamat");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 60, 60, 14);

        txtaddress.setText("jTextField2");
        getContentPane().add(txtaddress);
        txtaddress.setBounds(120, 50, 260, 30);

        jLabel3.setText("Umur");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(10, 100, 70, 14);

        txtage.setText("jTextField3");
        getContentPane().add(txtage);
        txtage.setBounds(120, 90, 260, 30);

        txtMathGrade.setText("jTextField4");
        getContentPane().add(txtMathGrade);
        txtMathGrade.setBounds(120, 130, 260, 30);

        jLabel4.setText("Matematika");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(10, 140, 70, 14);

        jLabel5.setText("B.inggris");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(10, 180, 60, 14);

        txtEnglishGrade.setText("jTextField5");
        getContentPane().add(txtEnglishGrade);
        txtEnglishGrade.setBounds(120, 170, 260, 30);

        jLabel6.setText("Pengetahuan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 230, 80, 14);

        txtScienceGrade.setText("jTextField6");
        txtScienceGrade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtScienceGradeActionPerformed(evt);
            }
        });
        getContentPane().add(txtScienceGrade);
        txtScienceGrade.setBounds(120, 220, 260, 30);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(10, 280, 80, 30);

        tabelStudentRecord.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama", "Umur", "Matematika", "B.Inggris", "Pengetahuan"
            }
        ));
        tabelStudentRecord.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelStudentRecordMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelStudentRecord);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(10, 322, 390, 160);

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });
        getContentPane().add(btnEdit);
        btnEdit.setBounds(100, 280, 51, 30);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(190, 280, 63, 30);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        getContentPane().add(btnCancel);
        btnCancel.setBounds(280, 280, 65, 30);

        setBounds(0, 0, 421, 529);
    }// </editor-fold>//GEN-END:initComponents

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        // TODO add your handling code here:
        controller.insert();
        controller.viewTabel();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void txtScienceGradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtScienceGradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtScienceGradeActionPerformed

    private void tabelStudentRecordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelStudentRecordMouseClicked
        controller.onClickTabel();
    }//GEN-LAST:event_tabelStudentRecordMouseClicked

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        controller.update();
        controller.viewTabel();
        controller.bersihForm();
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        controller.delete();
        controller.viewTabel();
        controller.bersihForm();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        controller.bersihForm();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormStudentRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormStudentRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelStudentRecord;
    private javax.swing.JTextField txtEnglishGrade;
    private javax.swing.JTextField txtMathGrade;
    private javax.swing.JTextField txtScienceGrade;
    private javax.swing.JTextField txtaddress;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtname;
    // End of variables declaration//GEN-END:variables
}
