
package Penjualan.view;

import Penjualan.controller.penjualanController;

public class View_Penjualan extends javax.swing.JFrame {

    penjualanController controller;
    
    public View_Penjualan() {
        initComponents();
        controller = new penjualanController(this);
        controller.bersihForm();
    }
    
    public javax.swing.JTextField getkd_faktur(){
        return kd_faktur;
    }
    
    public javax.swing.JTextField gettgl_Faktur(){
       return tgl_Faktur;
    }
    
    public javax.swing.JTextField getpelanggan(){
        return pelanggan;
    }
    
    public javax.swing.JTextField getnamaBrg(){
        return namaBrg;
    }
    
    public javax.swing.JTextField getharga(){
        return harga;
    }
    
    public javax.swing.JTextField getjumlah(){
        return jumlah;
    }
    
    public javax.swing.JTextField getsearch(){
        return search;
    }
    
    public javax.swing.JTable getlistData(){
        return listData;
    }
    
    public javax.swing.JTable getListFaktur(){
        return ListFaktur;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kd_faktur = new javax.swing.JTextField();
        search = new javax.swing.JTextField();
        btn_search = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tgl_Faktur = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        pelanggan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        namaBrg = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        harga = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jumlah = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        listData = new javax.swing.JTable();
        btnSimpan = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        Btn_Delete = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();
        btnInsert = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        ListFaktur = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Tempus Sans ITC", 0, 24)); // NOI18N
        jLabel1.setText("PENJUALAN");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(170, 0, 160, 30);

        jLabel2.setText("Kode Faktur");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 40, 80, 30);
        getContentPane().add(kd_faktur);
        kd_faktur.setBounds(100, 40, 170, 30);
        getContentPane().add(search);
        search.setBounds(280, 40, 110, 30);

        btn_search.setText("Cari");
        btn_search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_searchActionPerformed(evt);
            }
        });
        getContentPane().add(btn_search);
        btn_search.setBounds(400, 40, 51, 30);

        jLabel3.setText("Tgl. Faktur");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(20, 100, 60, 14);

        tgl_Faktur.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgl_FakturActionPerformed(evt);
            }
        });
        getContentPane().add(tgl_Faktur);
        tgl_Faktur.setBounds(100, 100, 170, 30);

        jLabel4.setText("Pelanggan");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(20, 160, 70, 14);
        getContentPane().add(pelanggan);
        pelanggan.setBounds(100, 150, 170, 30);

        jLabel5.setText("Nama Barang");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 220, 120, 14);

        namaBrg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaBrgActionPerformed(evt);
            }
        });
        getContentPane().add(namaBrg);
        namaBrg.setBounds(20, 250, 110, 30);

        jLabel6.setText("Harga");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(230, 220, 70, 10);
        getContentPane().add(harga);
        harga.setBounds(190, 250, 110, 30);

        jLabel7.setText("Jumlah");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(390, 220, 70, 14);

        jumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jumlahActionPerformed(evt);
            }
        });
        getContentPane().add(jumlah);
        jumlah.setBounds(360, 250, 130, 30);

        listData.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Barang", "Harga", "Jumlah", "Total"
            }
        ));
        listData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listDataMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listData);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(20, 330, 500, 120);

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan);
        btnSimpan.setBounds(20, 470, 90, 30);

        btnEdit.setText("Edit");
        getContentPane().add(btnEdit);
        btnEdit.setBounds(130, 470, 70, 30);

        Btn_Delete.setText("Delete");
        Btn_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_DeleteActionPerformed(evt);
            }
        });
        getContentPane().add(Btn_Delete);
        Btn_Delete.setBounds(240, 470, 70, 30);

        btnCancel.setText("Cancel");
        getContentPane().add(btnCancel);
        btnCancel.setBounds(350, 470, 80, 30);

        btnInsert.setText("Insert");
        btnInsert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInsertActionPerformed(evt);
            }
        });
        getContentPane().add(btnInsert);
        btnInsert.setBounds(360, 293, 61, 30);

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        getContentPane().add(btnDelete);
        btnDelete.setBounds(440, 293, 63, 30);

        ListFaktur.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Kode Faktur", "Tanggal Faktur", "Pelanggan"
            }
        ));
        ListFaktur.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ListFakturMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ListFaktur);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(550, 330, 370, 120);

        setBounds(0, 0, 945, 567);
    }// </editor-fold>//GEN-END:initComponents

    private void tgl_FakturActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgl_FakturActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgl_FakturActionPerformed

    private void jumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jumlahActionPerformed

    private void namaBrgActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaBrgActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaBrgActionPerformed

    private void btnInsertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInsertActionPerformed
        controller.insert();
        controller.viewData();
    }//GEN-LAST:event_btnInsertActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        controller.simpan();
        controller.viewDataFaktur();
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btn_searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_searchActionPerformed
        controller.cari();
    }//GEN-LAST:event_btn_searchActionPerformed

    private void listDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listDataMouseClicked
        // TODO add your handling code here:
        controller.cari();
    }//GEN-LAST:event_listDataMouseClicked

    private void Btn_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_DeleteActionPerformed
            controller.bersihForm();
    }//GEN-LAST:event_Btn_DeleteActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        controller.delete();
        controller.bersihForm();
        controller.viewData();
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void ListFakturMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ListFakturMouseClicked
        
    }//GEN-LAST:event_ListFakturMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(View_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(View_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(View_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(View_Penjualan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new View_Penjualan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Btn_Delete;
    private javax.swing.JTable ListFaktur;
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnInsert;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btn_search;
    private javax.swing.JTextField harga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jumlah;
    private javax.swing.JTextField kd_faktur;
    private javax.swing.JTable listData;
    private javax.swing.JTextField namaBrg;
    private javax.swing.JTextField pelanggan;
    private javax.swing.JTextField search;
    private javax.swing.JTextField tgl_Faktur;
    // End of variables declaration//GEN-END:variables
}
